# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

DEFAULTS: &DEFAULTS
  a_default: <%= ENV['A_DEFAULT_VALUE'] %>

development:
  secret_key_base: 66c9bc410f881ed86dedb6df5ab6516a2aee5757be2c5e55b95d636c087ad33364187e31142d2c1d0b40b784f14122463ced317f8200dfa4309a656471bbfcc3
  stripe_publishable_key: thisisadummykey
  stripe_secret_key: thisisadummykey
  default_mailer_host: localhost
  <<: *DEFAULTS

test:
  secret_key_base: 9dfc05f46e8d5ae90dfee74536de979e78d20fd584fdaa63116c6950a3b9dc86004855c3925139bb88519e982bc26b05647beeebb3ee691efd4425392de7e1b6
  stripe_publishable_key: thisisadummykey
  stripe_secret_key: thisisadummykey
  <<: *DEFAULTS

# Do not keep production secrets in the repository; instead, read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  default_mailer_from: <%= ENV['MAILER_DEFAULT_FROM'] %>
  default_mailer_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  <<: *DEFAULTS
